POST http://backqueue.info/v1/login/auth
content-type: application/json

{
	"username": "+78888888887",
	"password": 1111
}


###
GET http://backqueue.info/v1/cultures/bystevedoreid/5
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJxdW90YXMiLCJpYXQiOjE1NDA5MDMyNzIsImp0aSI6IjE2VWNhS2JuZ3dTdSIsIm5iZiI6MTU0MDkwMzI3NywiZXhwIjoxNTQwOTc1Mjc3LCJkYXRhIjp7ImlkIjoyNjU2NywibmFtZSI6Ilx1MDQyMlx1MDQzNVx1MDQ0MVx1MDQ0MiIsInJvbGUiOjIsInNhbHQiOiI2Z3FvNTZhbmJpIiwibW9ubyI6MCwiZXhwb3J0ZXJfaWQiOjAsIm11bHRpX2V4cG9ydGVyIjowLCJzdGV2ZWRvcmVfYWRtaW4iOjAsInJlZnJlc2hfdG9rZW4iOiJwOXRtcTB0VVlqM2F0LWhwZVBZUnZIWFcifX0.A_PzrnadFDiOrtHrjwsS-w3W3d0ZQwqtf0PLX_iicj0