
POST http://cms.info/v1/login/auth
content-type: application/json

{
	"username": "+79897741292",
	"password": 1215,
	"m_n": "K7sQjA8PE"
}

###

OPTIONS http://apicrm.port-tranzit.ru/v1/f/list
content-type: application/json


###
GET http://cms.info/v1/failures/getlist
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjbXMiLCJpYXQiOjE1NDk1MzQ2ODcsImp0aSI6InhzM1lJTGQxeHBzUSIsIm5iZiI6MTU0OTUzNDY5MiwiZXhwIjoxNTQ5NjA2NjkyLCJkYXRhIjp7ImlkIjoyMDQ3LCJtX24iOiJLN3NRakE4UEUiLCJzYWx0IjoielVwLW50dmxqcSIsInJlZnJlc2hfdG9rZW4iOiJMWGxLbE02Zm8xSmFycENkVEFsYjdxUmEiLCJyb2xlIjoyfX0.cPohbppkBJ7s61hmZ4VZSVQRDstJecydrfRXii17qT8