POST http://cms.info/v1/login/auth
content-type: application/json

{
	"username": "+79181111111",
	"password": 1111,
	"m_n": "K7sQjA8PE"
}


###
GET http://backqueue.info/v1/cultures/bystevedoreid/5
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjbXMiLCJpYXQiOjE1NDIyMjU2NzcsImp0aSI6IlpQZTlDTVU4OE9hWCIsIm5iZiI6MTU0MjIyNTY4MiwiZXhwIjoxNTQyMjk3NjgyLCJkYXRhIjp7ImlkIjozMCwibV9uIjoiSzdzUWpBOFBFIiwic2FsdCI6IkV5Zlc0RUZTZE8iLCJyZWZyZXNoX3Rva2VuIjoiWHJZV2Z0V2plQ3dycnFFRkY0REFnbk1uIiwicm9sZSI6Mn19.y8oMk8hA-iM-Lui0_YvKTeAi4NlOq7IqZC9-h80jq5M